### ISSUE TITLE
Mouse scroll wheel support

### ISSUE THREAD

**Issue by yioannides** [popov895/better-desktop-zoom#2]
Thank you for creating this very useful extension!

I wanted to ask whether it would be possible to also include mouse wheel support in the extension. Thank you for your great work!

**Comment by popov895** [comment]
There is already such an extension - [Desktop Zoom ](https://extensions.gnome.org/extension/5297/desktop-zoom). You can ask its author to add support for the version of GNOME you need.

**Comment by yioannides** [comment]
It's just that the extension you mentioned hasn't been updated since GNOME 43, so considering both extensions are written in Javascript, you could incorporate the mouse scroll function and enhance the functionality of your extension

**Comment by popov895** [comment]
Fixed with 96ab8b3cd3a6f8411d9dec7e80812d6fd9113984.

**Comment by yioannides** [comment]
Thank you for the update! I When I do Ctrl + Super + mouse scroll, I am only changing workspaces and I don't see a way to disable / modify that built-in feature.

**Comment by popov895** [comment]
This feature is disabled by default. You can enable it in the extension settings.

**Comment by yioannides** [comment]
Oh that's strange, the option just appeared for me, after restarting a couple of times. Sorry for the false alarm.
