### ISSUE TITLE
Cannot add shortcut with Alt + Super + <key>

### ISSUE THREAD

**Issue by yioannides** [popov895/better-desktop-zoom#4]
Sorry for the multiple issues, I just wanted to report that even though most modifier combination to seem to work, Alt + Super + <key> doesn't seem to register. It would be also great to have a mouse scroll shortcut option, as I'd personally like to use Alt + Super with all my extensions, thank you!

**Comment by popov895** [comment]
What exactly keyboard shortcut are you trying to register? Isn't it currently registered for any action?

**Comment by yioannides** [comment]
I was trying to register Alt + Super + = and would ideally like to use the same modifiers for the mouse scroll as well, if possible.

**Comment by popov895** [comment]
`Alt+Super+=` is the system shortcut for the "Zoom in" action. Unfortunately, it's not possible for an extension to override a system shortcut. Therefore, you first need to manually [disable](https://www.baeldung.com/linux/gnome-disable-specific-shortcuts) this system shortcut, and then you can register it for the extension.

**Comment by yioannides** [comment]
Thank you for letting me know, that works. Would it be also possible to modify the mouse scroll shortcut, if that's not a lot of trouble for you?

**Comment by popov895** [comment]
Fixed with 0267d2abbfb2c548db6bfe4297aa2c73430b3994.
